server:
  #设置端口
  port: 8888
  max-http-header-size: 4096
  tomcat:
    remote-ip-header: x-forward-for
    uri-encoding: UTF-8
    max-threads: 1000
#spring配置
spring:
  #数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.6.151:3306/qms
    username: chenning
    password: chenningDB021
    type: com.alibaba.druid.pool.DruidDataSource
    #druid 设置
    druid:
      filter: stat
      #初始化大小
      initial-size: 1
      #最小等待连接数量
      min-idle: 1
      #最大连接数
      max-active: 20
      #超时设置
      max-wait: 86400
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/static/flowable-modeler
flowable:
  # 关闭定时任务JOB
  async-executor-activate: false
  # 建表策略
  database-schema-update: false
  # 启用自动部署流程定义
  check-process-definitions: true
  # 启用db历史表
  db-history-used: true
  # 要使用的历史级别。
  history-level: audit
  # 自动部署的名称
  deployment-name: SpringBootAutoDeployment
  # 自动部署时查找流程的目录
  process-definition-location-prefix: classpath*:/processes/
#mybatis配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/*.xml
